kevinjroyston/ScrawlBrawl

.gitignore
ClientApp/src/app/app.component.html
ClientApp/src/app/fetch-data/fetch-data.component.css
ClientApp/src/app/fetch-data/fetch-data.component.html
ClientApp/src/app/nav-menu/nav-menu.component.html
Properties/launchSettings.json
RoystonGame.sln
TV/GameManager.cs
UnityProject/Assets/Scripts/Networking/TestClient.cs

frontend test changes

---

ClientApp/src/app/fetch-data/fetch-data.component.html
ClientApp/src/app/nav-menu/nav-menu.component.html
UnityProject/ProjectSettings/EditorSettings.asset
UnityProject/ProjectSettings/ProjectVersion.txt

Feedbackbranch2

---

TV/ControlFlows/WaitForUserInput_BlackholeInletConnector.cs
TV/DataModels/States/State.cs
TV/DataModels/States/UserStates/SimplePromptUserState.cs
TV/DataModels/Users/User.cs
TV/GameModes/BriansGames/BodyBuilder/GameStates/Gameplay_GS.cs
TV/Lobby.cs
UnityProject/Assets/Scenes/SampleScene.unity
UnityProject/Assets/Scripts/ComponentAugments/AutoScaleGridLayoutGroup.cs
UnityProject/Assets/Scripts/Networking/TestClient.cs
UnityProject/ProjectSettings/ProjectVersion.txt
Web/DataModels/UnityObjects/DynamicAccessor.cs
Web/DataModels/UnityObjects/IAccessorHashable.cs
Web/DataModels/UnityObjects/UnityImage.cs
Web/DataModels/UnityObjects/UnityView.cs
WordLists/nouns.txt

numerous bug fixes to timeout logic, signalr/unity client
Updated noun word list

Timeoutfixes

---

ClientApp/src/app/fetch-data/fetch-data.component.css
ClientApp/src/app/fetch-data/fetch-data.selectordirective.component.ts
Web/Controllers/Gameplay/CurrentContentController.cs

added some animation to selector

Selector tweaks

---

RoystonGame/ClientApp/src/app/lobby-management/lobby-management.component.css
RoystonGame/ClientApp/src/app/user-management/user-management.component.css

Commented out css entry to fix missing brush options

Commented out css entry to fix missing brush options

---

RoystonGame/ClientApp/src/app/aboutus/aboutus.component.html
RoystonGame/ClientApp/src/app/homepage/homepage.component.html

made it size better on mobile.

Minor tweaks the home page and about us page.

---

RoystonGame/ClientApp/src/app/drawingboard/drawingboard.component.html
RoystonGame/ClientApp/src/app/drawingboard/drawingboard.component.ts
RoystonGame/ClientApp/src/app/fetch-data/fetch-data.component.html
RoystonGame/ClientApp/src/app/fetch-data/fetch-data.drawingdirective.component.ts

also first attempt at fixing the pinch/zoom issue not working inside drawingboard

Added Undo option for drawingboard

---

src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/homepage-previews/FriendQuiz-description.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/lobby-descriptions/FriendQuiz-description.html

couple of minor tweaks:
wording on submit button restored
added 2 missing assets to avoid the 404 errors

Plr uitweaks

---

src/Backend/APIs/Controllers/Gameplay/CurrentContentController.cs
src/Backend/GameInfrastructure/GameManager.cs
src/Common/DataModels/Responses/Gameplay/DrawingPromptMetadata.cs
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingdirective.component.ts
src/WebFrontEnd/ClientApp/src/index.html

added simple storage option of drawing to local storage (used for self portrait)

local storage of drawings

---

src/Backend/Games/KevinsGames/Mimic/GameStates/CreateMimics_GS.cs
src/Backend/Games/KevinsGames/Mimic/GameStates/Setup_GS.cs
src/Common/DataModels/Responses/Gameplay/DrawingPromptMetadata.cs
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.scss
src/WebFrontEnd/ClientApp/src/app/shared/material.module.ts

Plr colorwork

---

src/WebFrontEnd/ClientApp/src/app/modules/lobby/components/gamemode-dialog/gamemode-dialog.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/interfaces/gamemodes.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingdirective.component.ts

added min max values to numeric game prompt inputs

Plr gamemodeminmax

---

src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.scss

trivial change,   switched the drawinboard cursor from a finger to a crosshair

changed drawing cursor to a crosshair instead of a finger

---

src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.scss

CSS tweaks to spacing in the fetch data components

---

src/WebFrontEnd/ClientApp/angular.json
src/WebFrontEnd/ClientApp/src/app/layout/footer/footer.component.html
src/WebFrontEnd/ClientApp/src/app/layout/footer/footer.ts
src/WebFrontEnd/ClientApp/src/app/modules/home/components/connect-section/connect.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/components/lobbyinstructions-dialog/lobbyinstructions-dialog.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/components/lobbyinstructions-dialog/lobbyinstructions-dialog.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/lobby.module.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.scss
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/iconbutton/iconbutton.component.scss
src/WebFrontEnd/ClientApp/src/styles.scss

Trello Items
- "Contact us" link at the bottom doesnt seem to be working? 
- slightly smaller min brush size. slightly bigger biggest size 
- Not clear how to start a lobby. (Download client button not very apparent)
- Remove facebook links

Frontend fixes

---

src/WebFrontEnd/ClientApp/src/app/core/http/fixedassets.ts
src/WebFrontEnd/ClientApp/src/app/core/http/gamemodelist.ts
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/home/components/gamemodes-section/gamemode-list/gamemode-list.component.html
src/WebFrontEnd/ClientApp/src/app/modules/home/components/gamemodes-section/gamemode-list/gamemode-list.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/home/components/gamemodes-section/gamemode/gamemode.component.html
src/WebFrontEnd/ClientApp/src/app/modules/home/components/gamemodes-section/gamemode/gamemode.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/components/gameinfo-dialog/gameinfo-dialog.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/components/gameinfo-dialog/gameinfo-dialog.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/components/gamemode-dialog/gamemode-dialog.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/components/gamemode-dialog/gamemode-dialog.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/gameassetdirective.component.ts

to learn more buttons and simple data sanitization

production ready front end changes

---

src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.scss

made up for my last massive PR by pushing this PR

quick fix so gallery drawing box does not appear tiny

---

src/Backend/Games/BriansGames/BattleReady/GameStates/ExtraSetupDrawing_GS.cs
src/Backend/Games/BriansGames/BattleReady/GameStates/SetupDrawings_GS.cs
src/Backend/Games/BriansGames/BodyBuilder/GameStates/Setup_GS.cs
src/WebFrontEnd/ClientApp/src/app/core/models/gallerytypes.ts
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.scss
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.scss
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/gallerypanel/gallerypanel.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/gallerypanel/gallerypanel.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/gallerytool/gallerytool.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/gallerytool/gallerytool.component.ts
src/WebFrontEnd/ClientApp/src/assets/GameAssets/game-css/BodyBuilder-waiting-css.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/game-css/BodySwap-waiting-css.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/game-css/ChaoticCoop-waiting-css.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/game-css/FriendQuiz-waiting-css.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/game-css/Imposter-waiting-css.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/game-css/Mimic-waiting-css.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/homepage-previews/ChaoticCoop-description.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/lobby-descriptions/ChaoticCoop-description.html
src/WebFrontEnd/ClientApp/src/styles.scss

Backend fix for gallery not appearing in the games
Fix for improperly named image files in previous upload
Fix for auto load most recent drawing

Plr quickfixofgallery

---

src/Backend/GameInfrastructure/ControlFlows/Exit/WaitForTrigger_StateExit.cs
src/Backend/GameInfrastructure/DataModels/States/UserStates/Prompts.cs
src/Backend/GameInfrastructure/DataModels/States/UserStates/SimplePromptUserState.cs
src/Backend/Games/BriansGames/BodyBuilder/GameStates/Gameplay_GS.cs
src/Backend/Games/BriansGames/ImposterDrawing/GameStates/MakeDrawings_GS.cs
src/Backend/Games/BriansGames/TwoToneDrawing/TwoToneDrawingGameMode.cs

removed default waiting hadler per comment in last PR

#SB-65 renamed chaotic cooperation to collaboration

---

src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.ts

race condition JS error was causing execution to stop and objects did not load until next refresh

fix for asset not loading on first attempt

---

src/Backend/APIs/Controllers/Gameplay/CurrentContentController.cs
src/Backend/APIs/Controllers/LobbyManagement/LobbyController.cs
src/Backend/GameInfrastructure/ControlFlows/WaitForUserInput_BlackholeInletConnector.cs
src/Backend/GameInfrastructure/DataModels/Enums/EndOfGameRestartType.cs
src/Backend/GameInfrastructure/DataModels/States/GameStates/EndOfGameState.cs
src/Backend/GameInfrastructure/Lobby.cs

[Inactivity] Remove inactive users from lobby. Don't wait for inactive users during prompts

---

src/Backend/Games/BriansGames/TwoToneDrawing/DataModels/GameModeOptionsEnum.cs
src/Backend/Games/BriansGames/TwoToneDrawing/GameStates/Setup_GS.cs
src/Backend/Games/BriansGames/TwoToneDrawing/TwoToneDrawingGameMode.cs
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.html
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.scss
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/home/components/hero-section/hero-section.component.scss
src/WebFrontEnd/ClientApp/src/app/utils/drawingutils.ts
src/WebFrontEnd/ClientApp/src/styles.scss

also added top toolbar and timer

improved display of some of the chaotic displays

---

src/Backend/APIs/Controllers/LobbyManagement/LobbyController.cs
src/Backend/APIs/DataModels/AuthenticatedUser.cs
src/Backend/GameInfrastructure/GameManager.cs
src/WebFrontEnd/ClientApp/src/app/core/core.module.ts
src/WebFrontEnd/ClientApp/src/app/core/services/gallery.service.ts
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingdirective.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/gallery/gallerypanel/gallerypanel.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/gallery/gallerypanel/gallerypanel.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/gallery/gallerytool/gallerytool.component.ts

Lobby creation and joining had several race conditions, many locks were added to avoid this.
Frontend gallery editor was broken at some point by a previous change. Refactored to a common gallery service (more work needed here to add an in memory cache)
Moved many alerts to use the notification service instead

Fixed backend race conditions. Fixed frontend gallery feature

---

src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.ts
src/WebFrontEnd/ClientApp/src/assets/GameAssets/suggestions/BodyBuilder.json
src/WebFrontEnd/ClientApp/src/assets/GameAssets/suggestions/ChaoticColors-2.json
src/WebFrontEnd/ClientApp/src/assets/GameAssets/suggestions/ChaoticColors-3.json
src/WebFrontEnd/ClientApp/src/assets/GameAssets/suggestions/ChaoticLayers-2.json
src/WebFrontEnd/ClientApp/src/assets/GameAssets/suggestions/ChaoticLayers-3.json

fix for store most recent drawing being called too often

---

src/Backend/Games/BriansGames/BattleReady/BattleReadyGameMode.cs
src/Backend/Games/BriansGames/BattleReady/DataModels/BattleReadyConstants.cs
src/Backend/Games/BriansGames/ImposterDrawing/DataModels/ImposterDrawingConstants.cs
src/Backend/Games/BriansGames/ImposterDrawing/ImposterDrawingGameMode.cs
src/Backend/Games/BriansGames/TwoToneDrawing/DataModels/TwoToneDrawingConstants.cs
src/Backend/Games/BriansGames/TwoToneDrawing/TwoToneDrawingGameMode.cs
src/Backend/Games/KevinsGames/Mimic/DataModels/MimicConstants.cs
src/Backend/Games/TimsGames/FriendQuiz/DataModels/FriendQuizConstants.cs
src/BackendTests/BackendTests.csproj
src/BackendTests/Games/GameModeMetadataTests.cs

Tweaked all duration values and added tool for displaying all the duration estimates

---

src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.ts

color was not properly displaying on the color picker

last used color was being set but 

---

src/Backend/Games/BriansGames/TwoToneDrawing/TwoToneDrawingGameMode.cs
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/join-game/join-game.module.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/lobby.module.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingdirective.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/gallery/gallerytool/gallerytool.component.ts

Just a bunch of minor tweaks to fix a couple of the errors I was seeing in the console / from our last testing session.

Misc bugfixes

---

src/WebFrontEnd/ClientApp/src/app/app.routing.ts
src/WebFrontEnd/ClientApp/src/app/core/http/userManager.ts
src/WebFrontEnd/ClientApp/src/app/layout/footer/footer.component.html
src/WebFrontEnd/ClientApp/src/app/layout/nav-menu/nav-menu.component.html
src/WebFrontEnd/ClientApp/src/app/layout/nav-menu/nav-menu.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/home/pages/home/home.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/join-game/pages/join-game/join-game.component.ts

redirect to join on game error

redirecting main page into game if in a game

---

src/Backend/APIs/Controllers/Gameplay/CurrentContentController.cs
src/Common/DataModels/Responses/Gameplay/CurrentContent.cs
src/WebFrontEnd/ClientApp/src/app/shared/components/displayusers/displayusers.component.css
src/WebFrontEnd/ClientApp/src/app/shared/components/waitingforgamestart/waitingforgamestart.component.css
src/WebFrontEnd/ClientApp/src/app/shared/components/waitingforgamestart/waitingforgamestart.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/waitingforgamestart/waitingforgamestart.component.ts

tweaks to user list display 
waiting for game start, added a placeholder that launches viewer if running on a PC (wide enough screen)

Stopping back end from returning prompts if id matches

---

src/Backend/APIs/Controllers/LobbyManagement/LobbyController.cs
src/WebFrontEnd/ClientApp/src/app/core/http/api.ts
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.scss
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/create-lobby/create-lobby.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/create-lobby/create-lobby.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.ts

Fixed Issue with timer going negative / counting twice as fast
Also changed CREATE logic so you can create a lobby or create and join.

Plr joincreatework

---

src/Backend/GameInfrastructure/Constants.cs
src/Backend/GameInfrastructure/ControlFlows/Exit/WaitForTimer_StateExit.cs
src/Backend/GameInfrastructure/ControlFlows/Exit/WaitForTrigger_StateExit.cs
src/Backend/GameInfrastructure/ControlFlows/Exit/WaitForUsers_StateExit.cs
src/Backend/GameInfrastructure/DataModels/States/GameStates/WaitForLobbyCloseGameState.cs
src/Backend/GameInfrastructure/DataModels/States/State.cs
src/Backend/GameInfrastructure/DataModels/Users/User.cs
src/Backend/GameInfrastructure/Lobby.cs
src/Backend/Games/BriansGames/BattleReady/GameStates/ContestantCreation_GS.cs
src/Backend/Games/Common/GameStates/QueryAndReveal/QueryAndRevealState.cs
src/Backend/Games/Common/GameStates/VoteAndReveal/VoteAndRevealState.cs
src/Backend/Games/KevinsGames/TextBodyBuilder/GameStates/ContestantCreation_GS.cs
src/Common/Code/Helpers/MemberHelpers.cs

Fixes recent crashes, player inactivity handling, and deadlock

Kev deadlockfix

---

src/Backend/Games/BriansGames/BattleReady/BattleReadyGameMode.cs
src/Backend/Games/BriansGames/ImposterDrawing/ImposterDrawingGameMode.cs
src/Backend/Games/BriansGames/TwoToneDrawing/GameStates/Setup_GS.cs
src/Backend/Games/BriansGames/TwoToneDrawing/TwoToneDrawingGameMode.cs
src/Backend/Games/KevinsGames/Mimic/MimicGameMode.cs
src/Backend/Games/KevinsGames/TextBodyBuilder/GameStates/ContestantCreation_GS.cs
src/Backend/Games/KevinsGames/TextBodyBuilder/GameStates/SetupCAMs_GS.cs
src/Backend/Games/KevinsGames/TextBodyBuilder/TextBodyBuilderGameMode.cs
src/Backend/Games/TimsGames/FriendQuiz/FriendQuizGameMode.cs

Small tweak to gamemode time estimates
Changed how the new gamemode works slightly. Users now type in a modifier during contestant creation rather than during setup

minor improvements

---

src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/waitingforgamestart/waitingforgamestart.component.ts

passing lobby id into waiting for game start.  I was sure I had added the input lobbyid in waitingforgamestart so I tweaked the file to get it to upload.  Apparently it was there already.

fetch data now passes the lobby id into waiting for game start

---

src/WebFrontEnd/ClientApp/src/app/core/http/viewerInjectable.ts
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/unity/unity.component.ts

Moved the viewer instanciation back into the viewer injectable.   Seems to work on the create a lobby embedded viewer.  Let me know if you want the commented code stripped before approval.

Viewer update

---

src/Backend/GameInfrastructure/DataModels/InMemoryConfiguration.cs
src/Backend/Games/BriansGames/BattleReady/GameStates/SetupDrawings_GS.cs
src/Backend/Games/BriansGames/BattleReady/GameStates/SetupPrompts_GS.cs
src/Backend/Games/BriansGames/ImposterDrawing/DataModels/Prompt.cs
src/Backend/Games/BriansGames/ImposterDrawing/GameStates/Setup_Gs.cs
src/Backend/Games/Common/GameStates/Setup/FixedCountSetupGameState.cs
src/Backend/Games/Common/GameStates/Setup/FurnishTrackerSetupGameState.cs
src/Backend/Games/KevinsGames/IMadeThis/DataModels/ChallengeTracker.cs
src/Backend/Games/KevinsGames/IMadeThis/DataModels/GameModeOptionsEnum.cs
src/Backend/Games/KevinsGames/IMadeThis/DataModels/IMadeThisConstants.cs
src/Backend/Games/KevinsGames/IMadeThis/GameStates/IMadeThisVoteAndReveal_Gs.cs
src/Backend/Games/KevinsGames/IMadeThis/GameStates/SetupImproveInitialDrawing_Gs.cs
src/Backend/Games/KevinsGames/IMadeThis/GameStates/SetupInitialDrawing_Gs.cs
src/Backend/Games/KevinsGames/IMadeThis/GameStates/SetupPrompts_Gs.cs
src/Backend/Games/KevinsGames/IMadeThis/IMadeThisGameMode.cs
src/Backend/Games/KevinsGames/LateToArtClass/DataModels/ArtClass.cs
src/Backend/Games/KevinsGames/LateToArtClass/GameStates/Setup_Gs.cs
src/Backend/Games/KevinsGames/LateToArtClass/LateToArtClassGameMode.cs
src/Backend/Games/KevinsGames/TextBodyBuilder/GameStates/SetupCAMs_GS.cs
src/Backend/Games/KevinsGames/TextBodyBuilder/GameStates/SetupPrompts_GS.cs
src/Backend/Games/TimsGames/FriendQuiz/GameStates/Setup_GS.cs
src/Common/DataModels/Enums/GameModeId.cs
src/Common/DataModels/Interfaces/Constraints.cs

Adds new gamemode, also fixes some concurrency bugs and other inconsistencies.
New gamemode should be a better example to copy off of than some of the other games

Adds new game '... I made this'

---

src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingdirective.component.ts

allowing drawing line size to go to 1 instead of min 3

improved icons for undo and enlarge viewer

---

src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.scss
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingdirective.component.ts

added a redo button to drawings

---

src/Backend/GameInfrastructure/DataModels/States/GameStates/WaitForLobbyCloseGameState.cs
src/Backend/GameInfrastructure/DataModels/States/UserStates/Prompts.cs
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.html
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/colorpicker/colorPicker.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/colorpicker/colorpicker.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.scss
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingdirective.component.ts
src/WebFrontEnd/ClientApp/src/assets/GameAssets/tutorials/OverDrawn-tutorial.html
src/WebFrontEnd/ClientApp/src/styles.scss

Improved timer accuracy
Showing snackbar message if behind schedule on x of y
Changed drawing frame color to match timer warning color
Added frame around draw box to better show when not seeing the whole drawing space.
Tweaked OverDrawn tutorial

timer, ui, color picker history improvements

---

src/WebFrontEnd/ClientApp/src/app/layout/nav-menu/nav-menu.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/components/commonoptions-dialog/commonoptions-dialog.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/colorpicker/colorpicker.component.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/tutorials/BodyBuilder-tutorial.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/tutorials/TextBodyBuilder-tutorial.html
src/WebFrontEnd/ClientApp/src/styles.scss

also improved drop shadow contrast.

changed menu to PLAY HOST and added return to play tab button in lobby

---

src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.html
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.scss
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/lobby-descriptions/BodyBuilder-description.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/lobby-descriptions/Mimic-description.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/tutorials/BodyBuilder-tutorial.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/tutorials/ChaoticCoop-tutorial.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/tutorials/Imposter-tutorial.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/tutorials/LateToArtClass-tutorial.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/tutorials/Mimic-tutorial.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/tutorials/OverDrawn-tutorial.html
src/WebFrontEnd/ClientApp/src/assets/GameAssets/tutorials/TextBodyBuilder-tutorial.html

made click of lobby id put it on clipboard

fixed null ref, hiding into lines of tutorial on show information

---

src/WebFrontEnd/ClientApp/src/app/layout/nav-menu/nav-menu.component.html
src/WebFrontEnd/ClientApp/src/app/layout/nav-menu/nav-menu.component.ts
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.ts

also fixed bad code in the navigation routine.

changed default top menu to link to play instead of join to reduce flicker

---

.github/workflows/azure-static-web-apps-lemon-beach-01c1aeb1e.yml
.github/workflows/azure-static-web-apps-lively-glacier-08ddcca1e.yml

Frontend deploys havent been succeeding, switching to newer versions of these packages

Attempting to fix issues with frontend github action deploy pipelines

---

src/Backend/APIs/Controllers/LobbyManagement/LobbyController.cs
src/WebFrontEnd/ClientApp/src/app/core/http/api.ts
src/WebFrontEnd/ClientApp/src/app/modules/fetch-data/pages/fetch-data/fetch-data.component.html
src/WebFrontEnd/ClientApp/src/app/modules/lobby/pages/lobby/lobby.component.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.html
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.scss
src/WebFrontEnd/ClientApp/src/styles.scss

SB-723 create lobby was still causing owner to go to play page on start game

Plr create play fix

---

src/WebFrontEnd/ClientApp/src/app/core/services/theme.service.ts
src/WebFrontEnd/ClientApp/src/app/shared/components/drawingboard/drawingboard.component.ts
src/WebFrontEnd/ClientApp/src/app/utils/drawingutils.ts

also made it adjust the background when theme changes

SB-712 - fixed background not changing with new gray color scheme. 

---

src/WebFrontEnd/ClientApp/src/app/modules/home/pages/home/home.component.scss

still some minor issues on tiny (likely obsolete) phone screen sizes.

SB-719 - logo size issues on smaller screens

---

src/WebFrontEnd/ClientApp/src/app/modules/home/pages/home/home.component.scss

Reverts kevinjroyston/ScrawlBrawl#360
Some bugs, reverting for now

Revert "SB-719 - logo size issues on smaller screens"

---

src/WebFrontEnd/ClientApp/src/app/modules/home/pages/home/home.component.scss

Reverting my revert. Wasn't the issue

Revert "Revert "SB-719 - logo size issues on smaller screens""
